# Generated by Django 5.1.5 on 2025-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=300, verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='foto')),
            ],
        ),
    ]
